CREATE DATABASE minecraft_calculator;
CREATE USER mpc_acc WITH LOGIN PASSWORD 'mpc_acc';
GRANT ALL PRIVILEGES ON DATABASE minecraft_calculator TO mpc_acc;

CREATE TABLE IF NOT EXISTS MINECRAFT_ITEM(
	CD       SERIAL PRIMARY KEY NOT NULL,
	NM       TEXT               NOT NULL UNIQUE,
	WORK_L   INT                NOT NULL,
	WORK_C   INT                NOT NULL CHECK(WORK_C >= 0) DEFAULT 0,
	VL_IDEAL INT                NOT NULL CHECK(VL_IDEAL > 0) DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ITEM_SELL(
	CD       SERIAL PRIMARY KEY NOT NULL,
	ID_ITEM  INT                REFERENCES MINECRAFT_ITEM(CD),
	QT_ITEM  INT                NOT NULL DEFAULT 1,
	VN_BUYER MONEY              NOT NULL,
	VN_GOV   MONEY              DEFAULT 0,
	VL_SELL  MONEY              NOT NULL,
	TMS_SELL TIMESTAMP          NOT NULL
);

CREATE TABLE IF NOT EXISTS SERVICE_SELL(
	CD              SERIAL PRIMARY KEY NOT NULL,
	ID_ITEM_SERVICE INT                REFERENCES MINECRAFT_ITEM(CD),
	QT_ITEM         INT                NOT NULL DEFAULT 1,
	VN_BUYER        MONEY              NOT NULL,
	VN_SVP          MONEY              NOT NULL DEFAULT 0,
	TMS_SELL        TIMESTAMP          NOT NULL
	
);
