# Generated by Django 2.2.25 on 2022-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('cd', models.IntegerField(primary_key=True, serialize=False)),
                ('item', models.TextField()),
                ('qtd', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime_sell', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
